source "https://rubygems.org"

gem 'jekyll'
group :jekyll_plugins do
    gem 'github-pages'
    gem 'jekyll-paginate'
    gem 'jekyll-sitemap'
    gem 'jekyll-gist'
    gem 'jekyll-feed'
    gem 'jekyll-include-cache'
    gem 'jekyll-remote-theme'
    gem 'jekyll-theme-documentation'
end
